package com.jtkj.led1248;

/**
 * STUB: the real R2.java is an 18k-line resource-id index generated by the
 * butterknife/R2 gradle plugin. jadx's decompiler (running against an
 * R8-shrunk build) aliased a handful of numeric literals inside
 * ILedClockUtils' LZSS compressor and power-limiting helpers to R2.attr
 * fields that happen to share the same integer value post-shrink. Those
 * call sites are NOT real Android resource lookups; they are plain int
 * constants that must be preserved byte-for-byte for the vendor algorithms
 * (LZSS window/lookahead sizing, RGB power-budget clamp) to stay
 * byte-identical. Only the four fields actually referenced from the copied
 * vendor sources are reproduced here, with their exact real values verified
 * against the full decompiled R2.java.
 */
public final class R2 {
    private R2() {}

    public static final class attr {
        private attr() {}

        /** ILedClockUtils.adjustPowerGraffiti: per-pixel RGB sum budget (612). */
        public static final int fabCustomSize = 612;

        /** ILedClockUtils.LzssCompress: encode ring-buffer size, N + F (512 + 18 - 1 = 529). */
        public static final int drawableTintMode = 529;

        /** ILedClockUtils.LzssCompress: binary-tree node array size, N + 1 + 256 (769). */
        public static final int itemTextAppearanceActive = 769;

        /** ILedClockUtils.LzssCompress: initial buffer fill position, N - F (512 - 18 = 494). */
        public static final int dependency = 494;
    }
}
